[package]
name = "bot-na-lista"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.90"
chrono = "0.4.38"
diesel = { version = "2.2.4", features = ["chrono", "postgres", "r2d2"] }
diesel_migrations = { version = "2.2.0", features = ["postgres"] }
log = "0.4.22"
pretty_env_logger = "0.5.0"
teloxide = { version = "0.13.0", features = ["webhooks-axum", "ctrlc_handler"] }
tokio = { version = "1.41.0", features = ["rt-multi-thread", "macros", "fs", "rt"] }
url = "2.5.2"
