# Generated by Django 4.0.1 on 2022-01-14 22:02

import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_enable_hstor_ext"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShoppingList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "people",
                    django.contrib.postgres.fields.hstore.HStoreField(db_index=True),
                ),
                (
                    "items",
                    django.contrib.postgres.fields.hstore.HStoreField(default=dict),
                ),
            ],
        ),
    ]
